### ISSUE TITLE
アイテム取得時のIndexError対応

### ISSUE THREAD

**Issue by kitabatake1013** [actlaboratory/TCV#118]
アイテム情報の取得中、以下のようなエラーが出て、アプリが不正終了することがある。

```
Traceback (most recent call last):
  File "d:\programming\actlab\tcv\app.py", line 91, in run
    _run(*args, **kwargs)
  File "d:\programming\actlab\tcv\manager.py", line 866, in run
    self.checkItem()
  File "d:\programming\actlab\tcv\manager.py", line 825, in checkItem
    "user": users[i],
IndexError: list index out of range
```

コンティニューコイン爆などが来たときに起きるらしい。
コイン爆は、ツイキャス内部では独立したアイテムでなく、コンティニューコインが５枚送られたものとして扱われるようだ。

**Comment by kitabatake1013** [comment]
1. コイン爆があるかどうかを調べる
2. あれば、その数×５枚を差し引いた分のユーザ名を取得する

という方法を考えたが、そもそもそれがコイン爆なのか、１人がコイン５枚を投げたのかを判断するすべがない。

**Comment by kitabatake1013** [comment]
実装の方針：

* 基本的には、これまで通り履歴の取得を試みる
* IndexErrorが起きそうなとき（取得できたユーザ名の数がアイテムの数よりも少ないとき）は、残りのユーザ名を「不明なユーザ」とする

**Comment by kitabatake1013** [comment]
テストできていないが、上記方針に基づいて実装。
